function Logo () {
    colorbit_51bit.drawColorBit(2, 0, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(1, 1, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(3, 1, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(3, 2, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(2, 3, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(2, 4, colorbit.colors(BitColors.Green))
    basic.pause(500)
    colorbit_51bit.clear()
    colorbit_51bit.drawColorBit(2, 0, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(3, 1, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(3, 2, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(2, 3, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(2, 4, colorbit.colors(BitColors.Green))
    basic.pause(500)
    colorbit_51bit.clear()
    colorbit_51bit.drawColorBit(2, 0, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(3, 1, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(2, 2, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(2, 4, colorbit.colors(BitColors.Green))
    basic.pause(500)
    colorbit_51bit.clear()
    colorbit_51bit.drawColorBit(2, 0, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(2, 1, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(2, 2, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(2, 4, colorbit.colors(BitColors.Green))
    basic.pause(2000)
    colorbit_51bit.clear()
}
function lysshow () {
    colorbit_51bit.drawColorBit(0, 0, colorbit.colors(BitColors.Red))
    colorbit_51bit.drawColorBit(1, 1, colorbit.colors(BitColors.Green))
    colorbit_51bit.drawColorBit(2, 2, colorbit.colors(BitColors.Blue))
    colorbit_51bit.drawColorBit(3, 3, colorbit.colors(BitColors.Yellow))
    colorbit_51bit.drawColorBit(4, 4, colorbit.colors(BitColors.Purple))
    for (let indeks = 0; indeks <= 48; indeks++) {
        colorbit_51bit.rotate(1)
        colorbit_51bit.show()
        basic.pause(80)
    }
    colorbit_51bit.clear()
}
let colorbit_51bit: colorbit.Strip = null
colorbit_51bit = colorbit.initColorBit(DigitalPin.P0, BitColorMode.RGB)
colorbit_51bit.setBrightness(255)
basic.forever(function () {
    colorbit_51bit.setMultiColor(true)
    colorbit_51bit.showScrollStringColor("Vitensenteret", colorbit.colors(BitColors.Blue))
    colorbit_51bit.clear()
    colorbit_51bit.setMultiColor(false)
    Logo()
    basic.pause(2000)
    lysshow()
    basic.pause(2000)
})
